### ISSUE TITLE
How do you configure the Docker Hub automated build?

### ISSUE THREAD

**Issue by kristiandupont** [ckulka/docker-multi-arch-example#2]
I've tried to replicate your approach in [this repo](https://github.com/kristiandupont/dvdrental-image). It was configured to build `./Dockerfile` which now doesn't exist anymore, but the configuration insists on knowing about one dockerfile, so I just chose one: 
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/847742/119222484-dbf53980-baf4-11eb-95ef-721c5b7ee3eb.png">

This seems wrong to me but at least the build starts. It fails on the post_push hook which might be a different issue, I am not sure. Can you tell me if I am on the right track?

**Comment by ckulka** [comment]
Hi @kristiandupont , can you post what error you get?

I would guess that you need to do two things:

1. Change the "Docker Tag" column for the `arm64v8.dockerfile` build from `latest` to `arm64v8`
2. Add a new build rule for the `amd64.dockerfile` with a "Docker Tag" of `amd64`

The first build might fail because the manifet cannot be pushed, since the referenced image tags (`arm64v8` or `amd64`) don't exist yet. Once both are available, any subsequeny builds should be successful.

Good luck!

PS. I see that this isn't clear in the instructions... I'll see how I can complete the steps.

**Comment by ckulka** [comment]
Hey there, let me know if the updated `README.md` helps.

Btw, I checked out your Dockerfiles and wanted to let you know that you don't need any of the QEMU stuff if you don't have `RUN` commands in your Dockerfile. Not sure if you won't have any or if that'll come later, just wanted to let you know.

**Comment by kristiandupont** [comment]
Ah, that makes more sense, thank you!
This is the output from the hook:
```
Executing post_push hook...
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 100 631 100 631 0 0 2961 0 --:--:-- --:--:-- --:--:-- 2976
14 8108k 14 1188k 0 0 2244k 0 0:00:03 --:--:-- 0:00:03 2244k 100 8108k 100 8108k 0 0 11.1M 0 --:--:-- --:--:-- --:--:-- 37.7M
time="2021-05-22T09:37:59Z" level=fatal msg="Inspect of image \"kristiandupont/dvdrental-image:amd64\" failed with error: manifest unknown: manifest unknown"
post_push hook failed! (1)
```

Also thank you for the point about qemu, I'll get rid of that. As you can tell, it's a trivially simple image that I just need for testing for some other libraries..

And thank you for providing this example, I would never have figured it out without it!

**Comment by ckulka** [comment]
No problem, happy to help 👍
